import Head from "next/head";
import Image from "next/image";
import {
  useSession,
  signIn,
  signOut,
} from "next-auth/react";
import Drink from "../public/assets/home.jpg";
import Navbar from "../components/navbar";
import Gin from "../components/gin";
import Vodka from "../components/vodka";


export default function Component(results) {
  const { data: session } = useSession()
  
  console.log(session)
  if(session) {
    return(
     <>
      <Head>
          <title>Foodies Cocktails</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
      <nav className="flex justify-center items-center">
      <Navbar session={session} />
      </nav>
     
      <Gin  />
      <Vodka />
      
    </>
    )
  }
  return(

   <>
   <Head>
          <title>Cocktails</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="grid grid-cols-1 sm:grid-cols-2 h-screen w-full">
          <div className="hidden sm:block h-fit w-full">
            <Image
              priority="true"
              className="h-screen w-full object-cover"
              src={Drink}
              alt="Food"
            />
          </div>
          <div className=" w-full mx-auto bg-blue-400 p-32 px-8 rounded-lg"> 
          <div className="flex flex-col justify-center text-white font-bold">
      <h1 className="flex justify-center pt-72">Please signed in  </h1> <br/>
      <div className="flex justify-center  ">
      <button onClick={() => signIn()} className='w-36 border bg-blue-400 rounded-2xl justify-center p-1'>Sign In</button>
      </div>
      </div>
            
         </div>     
      </div>
    
  </>
  )
}


// export async function getServerSideProps() {
  
//   const res = await fetch("https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=Gin")
//   const results = await res.json()
//   return {
//     props: {
//       results
//     },
//   };
//   };